[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
ffi = true
ast = true
build_info = true
via-ir = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read", path = "./" }]

# Project paths
solc_version = "0.8.26"
#auto_detect_solc = true


# Gas and optimization
optimizer = true
optimizer_runs = 200